window.ENV = {
    FIREBASE_API_KEY: '{{.Env.FIREBASE_API_KEY}}',
    FIREBASE_AUTH_DOMAIN: '{{.Env.FIREBASE_AUTH_DOMAIN}}',
    FIREBASE_PROJECT_ID: '{{.Env.FIREBASE_PROJECT_ID}}',
    FIREBASE_STORAGE_BUCKET: '{{.Env.FIREBASE_STORAGE_BUCKET}}',
    FIREBASE_MESSAGING_SENDER_ID: '{{.Env.FIREBASE_MESSAGING_SENDER_ID}}',
    FIREBASE_APP_ID: '{{.Env.FIREBASE_APP_ID}}',
    FIREBASE_MEASUREMENT_ID: '{{.Env.FIREBASE_MEASUREMENT_ID}}'
};